### ISSUE TITLE
timeout undefined

### ISSUE THREAD

**Issue by telunc** [vankasteelj/torrent-tracker#1]
I'm crashing on this line
```
/root/project/node_modules/torrent-tracker/index.js:132
            clearTimeout(self.transactionCache[transactionId].timeout);
                                                             ^

TypeError: Cannot read property 'timeout' of undefined
    at SendWrap.callback (/root/project/node_modules/torrent-tracker/index.js:132:62)
    at SendWrap.afterSend [as oncomplete] (dgram.js:409:8)
```

**Comment by vankasteelj** [comment]
Indeed, that does happen and I still havent figured out why. Note that I'm no longer actively maintaining this, because I switched my main torrent engine to webtorrent, hence I'm using https://github.com/webtorrent/bittorrent-tracker
